services:
  postgres:
    container_name: postgres-dev
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: guest-list
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "guest-list", "-U", "${POSTGRES_USER:-postgres}" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data


volumes:
  postgres-data:
    driver: local
    name: postgres-data
