services:
  postgres:
    container_name: postgres-dev
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: guest-list
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "guest-list", "-U", "${POSTGRES_USER:-postgres}" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
  guest-list:
    container_name: guest-list-dev
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/guest-list
      DB_USER: ${POSTGRES_USER:-postgres}
      DB_PASS: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - '8080:8080'
    depends_on:
      - postgres


volumes:
  postgres-data:
    driver: local
    name: postgres-data
