app:
  name: guest-list
  identifier: ${app.name}-${random.uuid}
  lockKeyPrefix: ${app.name}-

server:
  servlet:
    context-path: /
  error:
    include-message: always
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/guest-list}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
    open-in-view: true
  flyway:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/guest-list}
    user: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
    baseline-on-migrate: true
    locations: classpath:db/migration
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: NON_NULL
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
  aop:
    proxy-target-class: false
